#version: "3.9"

services:
  mira:
    image: sonnh911/openwrt:test
    container_name: mira
    hostname: MIRA
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - SYSLOG
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/snd
      - /dev/kmsg
      # Các device động sẽ được thêm qua docker-compose.override.yml
    volumes:
      - /sys:/sys:rw
      - /proc/asound:/host_proc_asound:ro
      - /proc/device-tree:/host_proc_dt:ro
      - /home/admin:/home/mgwp
      - /etc/netplan:/host-netplan
    ports:
      - "80:80"
      - "443:443"
    command: ["/sbin/init"]
